name: SurvivalGames
version: 1.0.0
main: de.tmxx.survivalgames.SurvivalGames
description: A SurvivalGames minigame extended with player abilities and kits
author: tmxx
api-version: '1.21.4'

libraries:
  - com.mysql:mysql-connector-j:9.2.0
  - org.apache.commons:commons-dbcp2:2.13.0
  - commons-io:commons-io:2.18.0
  - com.google.inject:guice:7.0.0
  - com.google.inject.extensions:guice-assistedinject:7.0.0